name: Android CI Bionic - Mesa 26.0.4 Upgrade

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew assembleDebug

    - name: Attach release in action
      uses: actions/upload-artifact@v4
      with:
       name: Winlator-Ludashi-Mesa26-Public
       path: ./app/build/outputs/apk/debug/app-debug.apk
