name: Android CI Bionic

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
        cache: gradle

    - name: Patch UI, Logic, and Config
      run: |
        ARRAYS_FILE="app/src/main/res/values/arrays.xml"
        if [ -f "$ARRAYS_FILE" ]; then
          sed -i '/<string-array name="graphics_driver_entries">/a \        <item>Vortek</item>' "$ARRAYS_FILE"
          sed -i '/<string-array name="graphics_driver_values">/a \        <item>vortek</item>' "$ARRAYS_FILE"
        fi

        STRINGS_FILE="app/src/main/res/values/strings.xml"
        if [ -f "$STRINGS_FILE" ]; then
          sed -i 's/<string name="app_name">.*<\/string>/<string name="app_name">Vortex<\/string>/g' "$STRINGS_FILE"
        fi

        LOGIC_FILE="app/src/main/java/com/winlator/cmod/ContainerDetailFragment.java"
        if [ -f "$LOGIC_FILE" ]; then
          sed -i 's/case "wrapper":/case "vortek":\n            case "wrapper":/g' "$LOGIC_FILE"
          sed -i '/if (graphicsDriver.equals("wrapper"))/s/)/ || graphicsDriver.equals("vortek"))/' "$LOGIC_FILE"
          sed -i '/case "vortek":/a \                driverPath = version.equals("2.1") ? "vortek/vortek-2.1.tzst" : "vortek/vortek-2.0.tzst";' "$LOGIC_FILE"
        fi

        JSON_FILE="app/src/main/assets/graphics_drivers.json"
        if [ -f "$JSON_FILE" ]; then
          sed -i '0,/\[/{s/\[/\[\n    {"name": "Vortek", "version": "vortek", "path": "vortek" },/}' "$JSON_FILE"
        fi

    - name: Build and Rename
      run: |
        chmod +x gradlew
        ./gradlew assembleDebug
        mv app/build/outputs/apk/debug/*.apk Vortex.apk

    - name: Upload Vortex
      uses: actions/upload-artifact@v4
      with:
       name: Vortex-Build
       path: Vortex.apk
